### ISSUE TITLE
Too many network requests

### ISSUE THREAD

**Issue by ghost** [gizmo49/starwars#1]
Every time I change the movie, all the characters are fetched again. If I see a movie and switch to a different one, I don't want to have to refetch all the characters again when I get back to the first movie.

In this usecase, movie characters will not ever change, so we could cache them for better user experience.

**Comment by gizmo49** [comment]
I fixed this by saving movie characters in the app state labeled properly by the movie index

**Comment by ghost** [comment]
Good job. The only concern I would have from a product perspective is my experience after "reloading" the app. I start over. It could be awesome if we could save it somewhere in the browser! (Please do not implement it, this is just feedback)
