### ISSUE TITLE
Sorting issue with gender

### ISSUE THREAD

**Issue by ghost** [gizmo49/starwars#3]
Gender shows a hand hovering on it, like it does with name and height. Name and height are clickable and they sort. But nothing happens when I click on gender.

**Comment by gizmo49** [comment]
Fixed! only (The Name and Height) are clickable now. Gender Filter Select works as you would expect. Thanks

**Comment by ghost** [comment]
But the spec says:

> Character list can be sorted by clicking on the table headers.

It does not say it should only be sortable by name/height.

**Comment by gizmo49** [comment]
My mistake, I  added support for that now.  I was confused  because there is already a select filter for gender

**Comment by ghost** [comment]
Seen, good job.
