### ISSUE TITLE
Character loading issue

### ISSUE THREAD

**Issue by ghost** [gizmo49/starwars#4]
It looks like characters are loading incrementally, this gives me false information when first few characters are loaded but the rest have not loaded yet. I feel there are a couple of characters in the film, then suddenly more begin appearing.

It would be much better if there were a loading placeholder until all characters are loaded and then they appeared once everything is fetched.

**Comment by gizmo49** [comment]
I fixed this by making an ASYNC and wait request, Characters show now only after being loaded properly.
Observe the loading text while the data is been fetched
