### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by ghost** [gizmo49/starwars#5]
I will provide general feedback soon but in the meantime, please feel free to pick an issue and fix it. You don't have to fix everything. I'd like to see you address a feedback and show me your iterative process.

Thank you.

I'll add my feedback to this issue soon.

**Comment by ghost** [comment]
My main concern with this codebase is that it is a single big file that does everything.

I would have preferred seeing a clear separation of concerns. For instance an app wrapper, a state component, a data component, and a few pure UI components such as movie selector, crawl, character list, list header, list item, footer.

A good article to read on this topic is https://reactjs.org/docs/thinking-in-react.html

Apart from this, the code looks imperative to me, as in, one needs to really read and try to understand what it is doing. A good way to eliminate this problem would have been to create smaller functions and use them in a functional style.

Finally, the mix of ES5/6 does not feel very right.

I'd like you to iterate once more on this codebase to fix the main code structure problem and break this down into at least a couple of main components so that I can see how you approach this.

Thank you.

**Comment by gizmo49** [comment]
Great. I went through the article. I have now separated my APP into further distinguishable components, you will observe the Crawl, Table and other classes, even the movie select dropdown.
I have also tried to simplify my code by sticking to a particular pattern, so It should be a whole lot easier to understand

**Comment by ghost** [comment]
Thank you @gizmo49 this is certainly a good improvement. I'm closing this now and I will soon email you again.
